/**
 * Build-time content snapshot.
 *
 * Fetches every read endpoint from the API and writes:
 *   - src/generated/content.ts   → typed `snapshot` used as SSG/initial data
 *   - src/generated/routes.json  → concrete /projects/:slug and /blog/:slug paths
 *
 * If the API is unreachable, it writes empty stubs so the build still succeeds
 * (dynamic pages then fall back to client-side rendering).
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const outDir = join(here, "..", "src", "generated");
const base = process.env.VITE_API_URL ?? "http://localhost:4000";

async function get(path) {
  const res = await fetch(base + path);
  if (!res.ok) throw new Error(`${path} → ${res.status}`);
  return res.json();
}

async function main() {
  mkdirSync(outDir, { recursive: true });

  let snapshot = {
    projects: [],
    posts: [],
    fullPosts: [],
    experience: [],
    skills: { categories: [], highlightedIntegrations: [] },
  };
  let routes = [];

  try {
    const [projects, posts, experience, skills] = await Promise.all([
      get("/api/projects"),
      get("/api/posts"),
      get("/api/experience"),
      get("/api/skills"),
    ]);
    const fullPosts = await Promise.all(posts.map((p) => get(`/api/posts/${p.slug}`)));

    snapshot = { projects, posts, fullPosts, experience, skills };
    routes = [
      ...projects.map((p) => `/projects/${p.slug}`),
      ...posts.map((p) => `/blog/${p.slug}`),
    ];
    console.log(
      `snapshot: ${projects.length} projects, ${posts.length} posts, ` +
        `${experience.length} experience, ${skills.categories.length} skill groups`
    );
  } catch (err) {
    console.warn(`snapshot: API unreachable at ${base} (${err.message}). Writing empty stub.`);
  }

  writeFileSync(
    join(outDir, "content.ts"),
    "// AUTO-GENERATED by scripts/snapshot-content.mjs — do not edit.\n" +
      "import type { Snapshot } from \"@/lib/types\";\n\n" +
      `export const snapshot: Snapshot = ${JSON.stringify(snapshot, null, 2)};\n`
  );
  writeFileSync(join(outDir, "routes.json"), JSON.stringify(routes, null, 2) + "\n");
}

main();
